# Generated by Django 3.1.5 on 2021-04-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicepresmain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Details',
            fields=[
                ('case_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('problem', models.TextField()),
            ],
        ),
    ]
