# Generated by Django 3.1.5 on 2021-04-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicepresmain', '0002_patient_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Table',
            fields=[
                ('case_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
        ),
    ]
