# Generated by Django 3.1.5 on 2021-04-23 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voicepresmain', '0003_doctor_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_table',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='patient_details',
            name='problem',
        ),
        migrations.AddField(
            model_name='doctor_table',
            name='Advice',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor_table',
            name='Diagnosis',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor_table',
            name='Prescription',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_details',
            name='Symptoms',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_details',
            name='case_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Closed', 'Closed')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='patient_details',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
