# Generated by Django 3.1.5 on 2021-04-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicepresmain', '0004_auto_20210423_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_details',
            name='problem',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
